### ISSUE TITLE
Suporte a mais exemplos

### ISSUE THREAD

**Issue by patrickalima98** [CapivaraJS/capivarajs#102]
Olá equipe do capivarajs, gostaria de perguntar a vocês sobre a possibilidade de fornecerem mais exemplos de como usar o framework de vocês, por exemplo vocês poderiam fornecer exemplos de integração do Vue, React e Angular não só pelo navegador como encontrado [aqui](https://jsfiddle.net/L5ya1t24/1/), mas também junto com os exemplos de CLIs de cada framework, isso ficaria muito mais completo e auxilia mais que está começando.

**Comment by mateusmirandaalmeida** [comment]
Ei @patrickalima98 beleza? Será que nosso repositorio de alguns componentes feitos em capivarajs já te ajudaria? De uma olhada em https://github.com/ui-capivara

**Comment by patrickalima98** [comment]
Olá, @mateusmirandaalmeida, sim eu dei uma olhada neles, o @jcanabarro  tinha me ajudado com isso, eu disse isso pelo fato de começar do zero com o framework de vocês e com o fato de novos usuários passarem a usarem o capivara, se tivesse mais exemplos, assim como tem no WebPack, no Vue.JS ficaria mais fácil começar.

**Comment by jcanabarro** [comment]
Todos os exemplos criados na documentação da versão 3.9.1 do Capivara, já possuem exemplos com múltiplos frameworks, logo logo ela será disponibilizada. 😄

**Comment by patrickalima98** [comment]
Blz, obrigado @jcanabarro!!!

**Comment by jcanabarro** [comment]
A nova documentação do Capivara, possui novos exemplos com Vue, Angular e React
